services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: sigr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - sigr_network

  # Administrador de base de datos (como phpMyAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sigr_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@sigr.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sigr_network
    depends_on:
      - postgres

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

# Red para comunicación entre contenedores
networks:
  sigr_network:
    driver: bridge